### ISSUE TITLE
Add metrics 

### ISSUE THREAD

**Issue by albertchon** [InjectiveLabs/peggo#44]
It's important to have monitoring and observability for peggo. 

We should: 
- [x] setup proper metrics configuration 
- [x] add metrics hooks everywhere 
- [x] create a peggo Grafana dashboard
- [x] deploy updated code on Mainnet/Testnet/Devnet

**Comment by albertchon** [comment]
Closed by https://github.com/InjectiveLabs/peggo/pull/45

**Comment by nhannamsiu** [comment]
Released  and updated peggo on mainnet validator nodes. Ref: https://grafana.injective.dev/d/zdByv9Mnk/peggo-metrics?orgId=1&refresh=30s&var-Interval=2m&var-Host=validator-us-0&var-env=prod
