### ISSUE TITLE
Add mempool API and batch tx submission offset

### ISSUE THREAD

**Issue by albertchon** [InjectiveLabs/peggo#46]
Peggo should really use a mempool API and have a configuration allowing for a custom time delay offset for batch tx submission so that we don't have so many failed tx's. 

E.g. Each one is ~$20+ flushed down the drain for no good reason
https://etherscan.io/address/0xdd14a1d791850ae9fdae9a29a0fe548b68f99116

**Comment by mankenavenkatesh** [comment]
Fixed in this PR - https://github.com/InjectiveLabs/peggo/pull/48
